### ISSUE TITLE
Passengers

### ISSUE THREAD

**Issue by Nathan-FiveM** [ChatDisabled/dc-christmasRadio#1]
Not sure why as no errors, tried to debug but I don't know much about the native audio stuff, when passengers are in the car it seems as though the driver or whoever changes the radio is the only one able to hear the Christmas radio station, native radio stations work correctly.

**Comment by ChatDisabled** [comment]
Unfortunate side effect of gamebuild 2944. Nothing I can do about as R* somehow changed how the radios work in the newest update. We haven't found a way yet to solve this :(. First mentioned this in my paid post

> Added an experimental config option for users using gamebuild 2944. A pretty annoying behaviour change was added which prevents custom stations to be synced across clients. Enabling this config option should alleviate it albeit a bit. Very hard to fix this manually.

https://forum.cfx.re/t/custom-native-radio-stations/5158461/21
